[package]
name = "allocate_memory"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52.0", features = ["Win32", "Win32_System", "Win32_System_Memory", "Win32_Foundation"] }
windows-core = "0.52.0"